com:
  cashtrack:
    cors:
      allowed-origin-patterns: http://*;https://*
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESQL_DATABASE_HOST}:${POSTGRESQL_DATABASE_PORT}/${POSTGRESQL_DATABASE_NAME}
    username: ${POSTGRESQL_DATABASE_USERNAME}
    password: ${POSTGRESQL_DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    driver-class-name: org.postgresql.Driver
    locations: db/migration
    password: ${POSTGRESQL_DATABASE_PASSWORD}
    url: jdbc:postgresql://${POSTGRESQL_DATABASE_HOST}:${POSTGRESQL_DATABASE_PORT}/${POSTGRESQL_DATABASE_NAME}
    user: ${POSTGRESQL_DATABASE_USERNAME}
jwt:
  key: ${JWT_KEY}
  access-token-expiration: 3600000 #ms
  refresh-token-expiration: 86400000 #ms