services:
  db:
    image: postgres:latest
    container_name: cashtrack-db
    command: 'postgres -c max_connections=1000 -c shared_buffers=128MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off'
    environment:
      POSTGRES_DB: ${POSTGRESQL_DATABASE_NAME}
      POSTGRES_USER: ${POSTGRESQL_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_DATABASE_PASSWORD}
    ports:
      - 5438:5432
    volumes:
      - postgres-container-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "--username", "${POSTGRESQL_DATABASE_USERNAME}", "--dbname", "${POSTGRESQL_DATABASE_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
  backend:
    image: cashtrack
    container_name: cashtrack_app
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - POSTGRESQL_DATABASE_URL=jdbc:postgresql://${POSTGRESQL_DATABASE_HOST}:${POSTGRESQL_DATABASE_PORT}/${POSTGRESQL_DATABASE_NAME}
      - POSTGRESQL_DATABASE_USERNAME=${POSTGRESQL_DATABASE_USERNAME}
      - POSTGRESQL_DATABASE_PASSWORD=${POSTGRESQL_DATABASE_PASSWORD}
      - JWT_KEY=${JWT_KEY}
volumes:
  postgres-container-data: